### ISSUE TITLE
Java Version

### ISSUE THREAD

**Issue by PulseBeat02** [caprica/vlcj-natives#4]
Hi, according to your latest Maven version, it says you are Java 8. I am trying to include this library in my project and I need to support Java 8 as most of the users that will use my project will use Java 8 mostly. Was the Java 11 specification in the pom.xml intended? If so, would I need to likely have to fork the project and modify the pom.xml and Java code to make it compatible with past versions?

**Comment by caprica** [comment]
Indeed no.

At one point I moved vlcj to use Java Module System and Java 11 as the baseline, but I undid that - although it seems not quite fully undone.

**Comment by caprica** [comment]
OK, I remember now...

The current version of vlcj-natives, used by the latest 4.x of vlcj, is actually 4.1.0, not 4.5.0.

4.5.0 was the abortive switch to the Java Modules System that has now been abandoned.

So I don't need make any changes here, although in theory I could revert the 4.5.0 vlcj-natives changes - but there's no real need to do that (I guess I thought I might come back to the Java Modules System, begrudgingly, at some point).

Anyway, check vlcj's pom, it references vlcj-natives 4.1.0, not 4.5.0.

**Comment by caprica** [comment]
So in case it's not clear, you won't have any problem unless you are explicitly adding vlcj-natives 4.5.0 to your project (which you should not do if you are using vlcj).

If you want to use vlcj-natives apart from vlcj, then use vlcj-natives 4.1.0.

**Comment by PulseBeat02** [comment]
Ah. I see now what you mean. That makes more sense. Thank you for the clarification! Great project by the way, I would never be able to have the time and effort to make something so great!

**Comment by caprica** [comment]
Thanks for the kind words.
